USE [IF5100_2022_SEIA_STORE]

EXEC [dbo].[sp_CreateTables]

SELECT * FROM STOCK.tb_DIM_PRODUCT;
SELECT * FROM [SALES].[tb_DIM_PAYMENT_METHOD];

CREATE SCHEMA CUSTOMERS
CREATE SCHEMA SALES
CREATE SCHEMA STOCK

CREATE TABLE CUSTOMERS.tb_CLIENT
(
CLIENT_ID  serial PRIMARY KEY NOT NULL
,CLIENT_NAME VARCHAR(25) NOT NULL
,CLIENT_LAST_NAME VARCHAR(25) NOT NULL
,IS_ACTIVE BIT NOT NULL DEFAULT '1'
,IS_DELETED BIT NOT NULL DEFAULT '0'
,LAST_MODIFIED_BY VARCHAR(25) DEFAULT user
,LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
)

CREATE TABLE CUSTOMERS.tb_PHONE
(
PHONE_ID serial PRIMARY KEY  NOT NULL
,PHONE_NUMBER VARCHAR(15) NOT NULL
,IS_ACTIVE BIT NOT NULL DEFAULT '1'
,IS_DELETED BIT NOT NULL DEFAULT '0'
,LAST_MODIFIED_BY VARCHAR(25) DEFAULT user
,LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
)

CREATE TABLE CUSTOMERS.tb_CLIENT_PHONES
(
CLIENT_ID INT NOT NULL
,PHONE_ID INT NOT NULL
,IS_ACTIVE BIT NOT NULL DEFAULT '1'
,IS_DELETED BIT NOT NULL DEFAULT '0'
,LAST_MODIFIED_BY VARCHAR(25) DEFAULT user
,LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
,CONSTRAINT FK_CLIENT FOREIGN KEY(CLIENT_ID) REFERENCES CUSTOMERS.tb_CLIENT(CLIENT_ID)
,CONSTRAINT FK_PHONE FOREIGN KEY(PHONE_ID) REFERENCES CUSTOMERS.tb_PHONE(PHONE_ID)
,CONSTRAINT PK_CUST_PHONE PRIMARY KEY(CLIENT_ID,PHONE_ID))

CREATE TABLE CUSTOMERS.tb_CREDIT_CARD
(
CREDIT_CARD_ID SERIAL PRIMARY KEY  NOT NULL
,CREDIT_CARD_NUMBER  bytea UNIQUE NOT NULL
,CREDIT_CARD_BRAND INT NOT NULL --1 VISA 2MC 3AMEX 
,EXPIRATION_MONTH SMALLINT NOT NULL
,EXPIRATION_YEAR SMALLINT NOT NULL
,CVV  bytea NOT NULL
,IS_ACTIVE BIT NOT NULL DEFAULT '1'
,IS_DELETED BIT NOT NULL DEFAULT '0'
,LAST_MODIFIED_BY VARCHAR(25) DEFAULT user
,LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
)
	
CREATE TABLE CUSTOMERS.tb_CLIENT_CREDIT_CARDS
(
CLIENT_ID INT NOT NULL
,CREDIT_CARD_ID INT NOT NULL
,IS_ACTIVE BIT NOT NULL DEFAULT '1'
,IS_DELETED BIT NOT NULL DEFAULT '0'
,LAST_MODIFIED_BY VARCHAR(25) DEFAULT user
,LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
,CONSTRAINT FK_CLIENT1 FOREIGN KEY(CLIENT_ID) REFERENCES CUSTOMERS.tb_CLIENT(CLIENT_ID)
,CONSTRAINT FK_CC FOREIGN KEY(CREDIT_CARD_ID) REFERENCES CUSTOMERS.tb_CREDIT_CARD(CREDIT_CARD_ID)
,CONSTRAINT PK_CUST_CC PRIMARY KEY(CLIENT_ID,CREDIT_CARD_ID)
)


CREATE TABLE CUSTOMERS.tb_CITY
(
CITY_ID SERIAL PRIMARY KEY  NOT NULL
,CITY_NAME VARCHAR(50) NOT NULL
,IS_ACTIVE BIT NOT NULL DEFAULT '1'
,IS_DELETED BIT NOT NULL DEFAULT '0'
,LAST_MODIFIED_BY VARCHAR(25) DEFAULT user
,LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
)

CREATE TABLE CUSTOMERS.tb_ADDRESS
(
ADDRESS_ID SERIAL PRIMARY KEY  NOT NULL
,CITY_ID INT NOT NULL
,DETAILS VARCHAR(200)
,IS_ACTIVE BIT NOT NULL DEFAULT '1'
,IS_DELETED BIT NOT NULL DEFAULT '0'
,LAST_MODIFIED_BY VARCHAR(25) DEFAULT user
,LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
,CONSTRAINT FK_CITY FOREIGN KEY (CITY_ID) REFERENCES CUSTOMERS.tb_CITY(CITY_ID)
)

CREATE TABLE CUSTOMERS.tb_CLIENT_ADDRESSES
(
CLIENT_ID INT NOT NULL
,ADDRESS_ID INT NOT NULL
,IS_ACTIVE BIT NOT NULL DEFAULT '1'
,IS_DELETED BIT NOT NULL DEFAULT '0'
,LAST_MODIFIED_BY VARCHAR(25) DEFAULT user
,LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
,CONSTRAINT FK_CLIENT2 FOREIGN KEY(CLIENT_ID) REFERENCES CUSTOMERS.tb_CLIENT(CLIENT_ID)
,CONSTRAINT FK_ADDRESS FOREIGN KEY(ADDRESS_ID) REFERENCES CUSTOMERS.tb_ADDRESS(ADDRESS_ID)
,CONSTRAINT PK_CUST_ADDRESS PRIMARY KEY(CLIENT_ID,ADDRESS_ID)
)

CREATE TABLE SALES.tb_CURRENCY
(
 CURRENCY_ID serial PRIMARY KEY NOT NULL
,CURRENCY_NAME VARCHAR(15) NOT NULL
,IS_ACTIVE BIT NOT NULL DEFAULT '1'
,IS_DELETED BIT NOT NULL DEFAULT '0'
,LAST_MODIFIED_BY VARCHAR(25) DEFAULT user
,LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
)
	
CREATE TABLE SALES.tb_PAYMENT_METHOD
(
PAYMENT_METHOD_ID serial PRIMARY KEY NOT NULL
,PAYMENT_METHOD_NAME VARCHAR(25) NOT NULL
,IS_ACTIVE BIT NOT NULL DEFAULT '1'
,IS_DELETED BIT NOT NULL DEFAULT '0'
,LAST_MODIFIED_BY VARCHAR(25) DEFAULT user
,LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
)
	
CREATE TABLE SALES.tb_INVOICE
(
INVOICE_ID serial PRIMARY KEY NOT NULL
,PURCHASE_DATE TIMESTAMP NOT NULL
,TOTAL_PRICE NUMERIC(9,3) NOT NULL
,CURRENCY_ID INT NOT NULL
,PAYMENT_METHOD_ID INT NOT NULL
,IS_ACTIVE BIT NOT NULL DEFAULT '1'
,IS_DELETED BIT NOT NULL DEFAULT '0'
,LAST_MODIFIED_BY VARCHAR(25) DEFAULT user
,LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
,CONSTRAINT FK_CURRENCY FOREIGN KEY(CURRENCY_ID) REFERENCES SALES.tb_CURRENCY(CURRENCY_ID)
,CONSTRAINT FK_PAYMENT_METHOD FOREIGN KEY(PAYMENT_METHOD_ID) REFERENCES SALES.tb_PAYMENT_METHOD(PAYMENT_METHOD_ID)
)
	
CREATE TABLE SALES.tb_CLIENT_INVOICE
(
CLIENT_ID INT NOT NULL
,INVOICE_ID INT NOT NULL
,IS_ACTIVE BIT NOT NULL DEFAULT '1'
,IS_DELETED BIT NOT NULL DEFAULT '0'
,LAST_MODIFIED_BY VARCHAR(25) DEFAULT user
,LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
,CONSTRAINT FK_CLIENT3 FOREIGN KEY(CLIENT_ID) REFERENCES CUSTOMERS.tb_CLIENT(CLIENT_ID)
,CONSTRAINT FK_INVOICE FOREIGN KEY(INVOICE_ID) REFERENCES SALES.tb_INVOICE(INVOICE_ID)
)

CREATE TABLE STOCK.tb_PRODUCT
(
PRODUCT_ID serial PRIMARY KEY NOT NULL
,PRODUCT_NAME VARCHAR(100) NOT NULL
,PRODUCT_PRICE NUMERIC(9,3) NOT NULL
,IS_ACTIVE BIT NOT NULL DEFAULT '1'
,IS_DELETED BIT NOT NULL DEFAULT '0'
,LAST_MODIFIED_BY VARCHAR(25) DEFAULT user
,LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
)

CREATE TABLE SALES.tb_INVOICE_DETAILS
(
INVOICE_DETAILS_ID serial PRIMARY KEY NOT NULL
,PRODUCT_ID INT NOT NULL
,INVOICE_ID INT NOT NULL
,PRODUCT_AMOUNT INT NOT NULL
,SUBTOTAL_PRICE NUMERIC(9,3) NOT NULL
,IS_ACTIVE BIT NOT NULL DEFAULT '1'
,IS_DELETED BIT NOT NULL DEFAULT '0'
,LAST_MODIFIED_BY VARCHAR(25) DEFAULT user
,LAST_MODIFIED_DATE TIMESTAMP DEFAULT NOW()
,CONSTRAINT FK_PRODUCT1 FOREIGN KEY(PRODUCT_ID) REFERENCES STOCK.tb_PRODUCT(PRODUCT_ID)
,CONSTRAINT FK_INVOICE FOREIGN KEY(INVOICE_ID) REFERENCES SALES.tb_INVOICE(INVOICE_ID)
)


CREATE TABLE STORE
(
	
STORE_NAME VARCHAR(40) NOT NULL
)
SELECT * FROM [SALES].[tb_DIM_INVOICE_DATE];
SELECT * FROM [SALES].[tb_FACT_TABLE_INVOICE];