CREATE PROCEDURE [dbo].[sp_CreateTables]
AS
BEGIN
	BEGIN TRY

			IF EXISTS(SELECT * FROM sysobjects WHERE type = 'U' AND name = 'tb_FACT_TABLE_INVOICE')
			BEGIN

				DROP TABLE SALES.tb_FACT_TABLE_INVOICE;           
				
			END

			IF EXISTS(SELECT * FROM sysobjects WHERE type = 'U' AND name = 'tb_DIM_PAYMENT_METHOD') 
			BEGIN

				DROP TABLE SALES.tb_DIM_PAYMENT_METHOD;           
				
			END

			IF EXISTS(SELECT * FROM sysobjects WHERE type = 'U' AND name = 'tb_DIM_INVOICE_DATE') 
			BEGIN

				DROP TABLE SALES.tb_DIM_INVOICE_DATE;           
				
			END

			IF EXISTS(SELECT * FROM sysobjects WHERE type = 'U' AND name = 'tb_DIM_PRODUCT')
			BEGIN

				DROP TABLE STOCK.tb_DIM_PRODUCT;           
				
			END

			CREATE TABLE STOCK.tb_DIM_PRODUCT
			(
			 PRODUCT_ID INT PRIMARY KEY NOT NULL
			,PRODUCT_NAME VARCHAR(100) NOT NULL
			,PRODUCT_PRICE NUMERIC(9,3) NOT NULL
			)

			CREATE TABLE SALES.tb_DIM_INVOICE_DATE
			(
			 INVOICE_PURCHASE_DATE_ID INT PRIMARY KEY NOT NULL
			,PURCHASE_DATE DATE NOT NULL
			,PURCHASE_YEAR VARCHAR(10) NOT NULL
			,PURCHASE_MONTH VARCHAR(10) NOT NULL
			)

			CREATE TABLE SALES.tb_DIM_PAYMENT_METHOD
			(
			 PAYMENT_METHOD_ID INT PRIMARY KEY NOT NULL
			,PAYMENT_METHOD VARCHAR(25) NOT NULL
			)

			CREATE TABLE SALES.tb_FACT_TABLE_INVOICE
			(
			 FACT_TABLE_INVOICE_ID INT PRIMARY KEY NOT NULL
			,INVOICE_PURCHASE_DATE_ID INT NOT NULL
			,PAYMENT_METHOD_ID INT NOT NULL
			,PRODUCT_ID INT NOT NULL
			,PRODUCT_AMOUNT INT NOT NULL
			,SUBTOTAL_PRICE NUMERIC(9,3) NOT NULL
			,TOTAL_PRICE NUMERIC(9,3) NOT NULL
			,CONSTRAINT FK_PAYMENT_METHOD_ID FOREIGN KEY(PAYMENT_METHOD_ID) REFERENCES SALES.tb_DIM_PAYMENT_METHOD(PAYMENT_METHOD_ID)
			,CONSTRAINT FK_INVOICE_PURCHASE_DATE_ID FOREIGN KEY(INVOICE_PURCHASE_DATE_ID) REFERENCES SALES.tb_DIM_INVOICE_DATE(INVOICE_PURCHASE_DATE_ID)
			,CONSTRAINT FK_PRODUCT_ID FOREIGN KEY(PRODUCT_ID) REFERENCES STOCK.tb_DIM_PRODUCT(PRODUCT_ID)
			)
		
	END TRY
	BEGIN CATCH

		PRINT ERROR_MESSAGE()

	END CATCH
END
GO